name: "unit-tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Basic test
    - uses: ./
      id: pkg_version
      with:
        package: flask
        language: python
    
    - name: Display latest package version
      run: |
        echo "${{ steps.pkg_version.outputs.latestVersion }}"

    # Search for a specific python version
    - uses: ./
      with:
        package: flask
        language: python
        conditions: |
          pythonVersion: py2

    # Search for a specific python version
    - uses: ./
      with:
        package: flask
        language: python
        conditions: |
          pythonVersion: 2.7

    # Search for a required python version
    - uses: ./
      with:
        package: flask
        language: python
        conditions: |
          requiresPython: 2.5
